openapi: 3.0.0
servers:
  - url: https://__API_URL__
info:
  title: __TITLE__
  description:
    <h1>__Инструкция по написанию ботов 👉 [<font size="5">тут</font>](botTutorial.html)__</h1>
    <h1>__Ответы на вопросы [<font size="5">FAQ</font>](FAQbotApi.html)__</h1>
    <h2>__Готовые библиотеки:__</h2>
    <ul>
      <li>[Python](https://github.com/mail-ru-im/bot-python) (<a href="https://pypi.org/project/mailru-im-bot/">PIP</a>)</li>
      <li>[Golang](https://github.com/mail-ru-im/bot-golang)</li>
      <li>[Java](https://github.com/mail-ru-im/bot-java)</li>
    </ul>
    <h1>__Прямая работа с API__</h1>
    <h2>__Создание бота__</h2>
    <p>Для создания учетной записи бота, обратитесь к [Метаботу](https://__PROFILE_URL__70001)</p>
    <h2>__Авторизация бота__</h2>
    <p>Каждый бот при создании получает уникальный токен аутентификации. Токен необходимо передавать в каждом запросе. Пример токена&#58;
    <pre><code>001.2659914704.0218887601:747432131</code></pre>
    <h2>__Отправка запросов__</h2>
    <p>Все запросы к Bot API необходимо выполнять по протоколу HTTPS.</p>
    <p>API поддерживает GET и POST методы. Параметры передаются двумя способами&#58;
      <ul>
        <li>[URL query string](https://en.wikipedia.org/wiki/Query_string)</li>
        <li>[multipart/form-data](https://ru.wikipedia.org/wiki/Multipart/form-data) (используется для загрузки файлов)</li>
      </ul>
    </p>
    <p>Названия методов и передаваемые параметры чувствительны к регистру.</p>
    <p>Ограничения на максимальный размер запросов&#58; 64 КБ для query string и 50 МБ для тела запроса.</p>
    <h2>__Обработка ответов__</h2>
    <p>Ответ представляет из себя JSON объект, в котором всегда есть boolean поле `ok`, отражающее статус выполнения запроса (true или false). Также может быть необязательное string поле `description` c детальным описанием результата.</p>
    <h2>__Получение событий от сервера__</h2>
    <p>Для получения серверных событий используйте методы из группы __events__ в режиме
    [long polling](http://en.wikipedia.org/wiki/Push_technology#Long_polling) запроса.
    <h2>__Изменения API__</h2>
    <p>20.03.2020:</p>
    <ul>
      <li>Добавили метод `/messages/answerCallbackQuery` и событие `callbackQuery` для работы с кнопками</li>
      <li>Добавили новое поле `inlineKeyboardMarkup` в тело запроса методов `/messages/editText`, `/messages/sendFile`, `/messages/sendText` и `/messages/sendVoice`</li>
    </ul>
    <p>05.03.2020:</p>
    <ul>
      <li>Добавили методы для модерации чатов `/chats/getMembers`, `/chats/getBlockedUsers`, `/chats/getPendingUsers`, `/chats/blockUser`, `/chats/unblockUser`, `/chats/resolvePending`, `/chats/setTitle`, `/chats/setAbout`, `/chats/setRules`</li>
    </ul>
    <p>29.01.2020:</p>
    <ul>
      <li>Добавили возможность в поле `chatId` передавать ник пользователя или чата</li>
    </ul>
    <p class='chat_link'><br>Если у вас остались вопросы, напишите нам в чат [Вопросы по ботам](https://__PROFILE_URL__AoLE1J5Ecm5DIjZh1gg)</p>

tags:
  - name: self
  - name: messages
  - name: chats
  - name: files
  - name: events
paths:
  /self/get:
    $ref: 'self/get.json'
  /messages/sendText:
    $ref: 'messages/sendText.json'
  /messages/sendFile:
    $ref: 'messages/sendFile.json'
  /messages/sendVoice:
    $ref: 'messages/sendVoice.json'
  /messages/editText:
    $ref: 'messages/editText.json'
  /messages/deleteMessages:
    $ref: 'messages/deleteMessages.json'
  /messages/answerCallbackQuery:
    $ref: 'messages/answerCallbackQuery.json'
  /chats/sendActions:
    $ref: 'chats/sendActions.json'
  /chats/getInfo:
    $ref: 'chats/getInfo.json'
  /chats/getAdmins:
    $ref: 'chats/getAdmins.json'
  /chats/getMembers:
    $ref: 'chats/getMembers.json'
  /chats/getBlockedUsers:
    $ref: 'chats/getBlockedUsers.json'
  /chats/getPendingUsers:
    $ref: 'chats/getPendingUsers.json'
  /chats/blockUser:
    $ref: 'chats/blockUser.json'
  /chats/unblockUser:
    $ref: 'chats/unblockUser.json'
  /chats/resolvePending:
    $ref: 'chats/resolvePending.json'
  /chats/setTitle:
    $ref: 'chats/setTitle.json'
  /chats/setAbout:
    $ref: 'chats/setAbout.json'
  /chats/setRules:
    $ref: 'chats/setRules.json'
  /chats/pinMessage:
    $ref: 'chats/pinMessage.json'
  /chats/unpinMessage:
    $ref: 'chats/unpinMessage.json'
  /files/getInfo:
    $ref: 'files/getInfo.json'
  /events/get:
    $ref: 'events/get.json'
