openapi: 3.0.0
servers:
  - url: https://__API_URL__
info:
  title: __TITLE__
  description: ICQ New Bot API

tags:
  - name: self
  - name: messages
  - name: chats
  - name: files
  - name: events
paths:
  /self/get:
    $ref: 'self/get.json'
  /messages/sendText:
    $ref: 'messages/sendText.json'
  /messages/sendFile:
    $ref: 'messages/sendFile.json'
  /messages/sendVoice:
    $ref: 'messages/sendVoice.json'
  /messages/editText:
    $ref: 'messages/editText.json'
  /messages/deleteMessages:
    $ref: 'messages/deleteMessages.json'
  /messages/answerCallbackQuery:
    $ref: 'messages/answerCallbackQuery.json'
  /chats/sendActions:
    $ref: 'chats/sendActions.json'
  /chats/getInfo:
    $ref: 'chats/getInfo.json'
  /chats/getAdmins:
    $ref: 'chats/getAdmins.json'
  /chats/getMembers:
    $ref: 'chats/getMembers.json'
  /chats/getBlockedUsers:
    $ref: 'chats/getBlockedUsers.json'
  /chats/getPendingUsers:
    $ref: 'chats/getPendingUsers.json'
  /chats/blockUser:
    $ref: 'chats/blockUser.json'
  /chats/unblockUser:
    $ref: 'chats/unblockUser.json'
  /chats/resolvePending:
    $ref: 'chats/resolvePending.json'
  /chats/setTitle:
    $ref: 'chats/setTitle.json'
  /chats/setAbout:
    $ref: 'chats/setAbout.json'
  /chats/setRules:
    $ref: 'chats/setRules.json'
  /chats/pinMessage:
    $ref: 'chats/pinMessage.json'
  /chats/unpinMessage:
    $ref: 'chats/unpinMessage.json'
  /files/getInfo:
    $ref: 'files/getInfo.json'
  /events/get:
    $ref: 'events/get.json'
